language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
#services:
#- mysql
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS spring;'
script:
- mvn -Dtest=**/*Test test
- mvn -Dtest=**/*IT package
- mvn -Dtest=**/*FunctionalTesting verify
