language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
#services:
#- mysql
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS spring;'
script:
- mvn -Dtest=**/*Test test
# Integration Test
- if [ $TRAVIS_TEST_RESULT == 0 ];
     then  mvn -Dtest=**/*IT package; 
     else  echo "ERRORES!!! ... se saltan los test de integracion"; 
  fi
- if [ $TRAVIS_TEST_RESULT == 0 ];
     then  -Dtest=**/*FunctionalTesting verify;
     else  echo "ERRORES!!! ... se saltan los test de funcionalidad"; 
  fi
