language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
#services:
#- mysql
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS spring;'
script:
# Test
- mvn -Dtest=**/*Test test
# Integration Test
- if [ $TRAVIS_TEST_RESULT == 0 ];
     then  mvn -Dtest=**/*IT package; 
     else  echo "ERRORES!!! ... se abortan resto de test"; 
  fi
# Functional Testing
- if [ $TRAVIS_TEST_RESULT == 0 ];
     then  mvn -Dtest=**/*FunctionalTesting verify;
     else  echo "ERRORES!!! ... se abortan resto de test"; 
  fi
deploy:
  provider: heroku
  api_key:
    secure: 92cc739d-ed70-411e-a343-f39367a5c249
  app: betca-spring
  on:
    repo: miw-upm/BETCA-spring
    branch: develop
